### ISSUE TITLE
Securing UI

### ISSUE THREAD

**Issue by ericdfields** [jcgertig/react-pundit#1]
I've been looking into the best way to secure UI components behind a permissions system, and this project looks like it would help.

However, it this is part of a bundled blob of JS delivered to a browser, you could ultimately flip bits using react devtools or similar methods, correct? 

The only way I've read to truly secure a UI is to not deliver it to the client at all. This would mean some tricky code splitting, I think. 

Do we know if this problem has been tackled in a react app before?

**Comment by jcgertig** [comment]
If you are doing server side render and normal code splitting along with this library then it would not get to the front end. But unless you go full server side rendered and dont use react on the client at all other than for small functionality but not routing or permission control then A fully secure app as you put it would not be possible.
