### ISSUE TITLE
VisibleIf working incorrectly?

### ISSUE THREAD

**Issue by tommyalvarez** [jcgertig/react-pundit#2]
Hi!
I'm working with react-pundit 2.0.0. Today i discovered that children inside `<VisibleIf>` are being mounted in spite of the policy returning false (hence, _passesPermissions_ returning false). By debugging this library i could confirm that _passesPermissions_ method  is returning false, so the component VisibleIf returns null in its render method. However, and maybe this is a misunderstanding of how react works, in that case, shame on me :),  if i put `console.log` statements inside a `<VisibleIf>`, they end up in the browser console so... they are probably being mounted anyway but not rendered? 
The problem with this is that required props for the children nested inside the `<VisibleIf>` triggers warnings and errors when it shouldn't. Is this a concept i understood wrongly? 

The code:

```
<PunditTypeSet type={props.punditType}>
  <VisibleIf action='destroy' model={props.record}>
        <ConfirmDialog
          body={I18n.t('views.shared.dialogs.confirmation.message')}
          cancelText={I18n.t('views.shared.dialogs.confirmation.cancel')}
          confirmText={I18n.t('views.shared.dialogs.confirmation.confirm')}
          loading={props.loading}
          onConfirm={props.onDestroy}
          onConfirmProps={props.record.id}
          title={I18n.t('actions.confirm')} />
  </VisibleIf>
</PunditTypeSet>
```

The thing is, that sometimes when destroy is not allowed, props.onDestroy of course does not exist, but `<ConfirmDialog>` requires it as a prop. I though that if destroy was not allowed, nothing inside VisibleIf was rendered or mounted.

**Comment by jcgertig** [comment]
This is react. The child here `ConfirmDialog` will have the prop types checked even if it does not get rendered because the class constructor will be called even though render dose not happen. So `onConfirm` could be set to not required or you could have something akin to `onConfirm={props.onDestroy || noop}`.

**Comment by jcgertig** [comment]
or set a default prop for `onDestroy` to a noop
